name: main
on: [workflow_dispatch]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Run unit tests
      run: yarn test
  
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Run e2e tests
      run: yarn test:e2e
