name: tests_pipeline
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    
  unit:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Run unit tests
      run: yarn test
  
  e2e:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Run e2e tests
      run: yarn test:e2e
